### ISSUE TITLE
Error in running TE-analysis_Shuffle_bed.pl

### ISSUE THREAD

**Issue by TaoHJiang** [4ureliek/TEanalysis#6]
Hi Aurelie,
I was trying to run TE-analysis_Shuffle_bed.pl
My command is :
perl TE-analysis_Shuffle_bed.pl -f input.bed -q repeatmask.out -r chrom.sizes -s tss -a Downlod_ensemble.gtf

Then,the script reports WARN "WARN: distance to TSS is so large (41663 nt) that once randomized this TE".
Is there something wrong with my files or the script? Would you help me with this?
Thank you

**Comment by 4ureliek** [comment]
This is just a warning; it will happen a lot with fragmented assemblies, or if TSS annotation is incomplete (e.g if only coding genes annotated). The function giving it is [here](https://github.com/4ureliek/TEanalysis/blob/df226fb68c369cfc979ab09906aa76aadaafa369/Lib/TEshuffle.pm#L468). It checks whether the position of the TE ended up outside of the genomic sequence, and corrects if it ends up outside of it. Note that this will tend to bias the randomization at the extremities of the genomic sequences. 

Note that -s rm will give very different results, and I would check that too (it depends what question you're asking; they aren't testing the same thing).

**Comment by TaoHJiang** [comment]
Thanks for your reply, May I assume that the warning will not affect the result of TE enrichment, or i need to try other  parameters?

**Comment by 4ureliek** [comment]
Well, it depends how many warnings; depends a lot on the TSS density and how fragmented the assembly is so I cannot definitely answer this.
If TEs are always very far from an annotated TSS, and the genomic units (contigs, scaffolds, chromosomes...) are small, then they are likely to fall out of the units; they get flipped around first, so TEs could end up placed far from the ends non randomly; and if they are still out when flipped they are simply put at the end, so that would be another bias.

The `-s rm` unit moves TEs around in existing locations, so it would test better specific families enrichment/depletion around surrounding features. TE insertion/retention is not random in the first place anyway... lots of biases depending on the TE families.

**Comment by TaoHJiang** [comment]
Actually, There are many warnings in log file, and as you said，when  TEs are  very far from an annotated TSS, they wolud  get flipped around the other side of the tss.  But only a fraction of them are still still out.  So, I think the results are authentic.  Of course, I will try the parameter "-s rm"  to compare my current result anyway.
Thank you for your advice.

**Comment by TaoHJiang** [comment]
I used "-s rm" parameter to re-analyze, and found that the results were not significant, which were quite different from previous results with "-s tss"

**Comment by 4ureliek** [comment]
That's 100% expected - they are not testing the same thing...!

**Comment by TaoHJiang** [comment]
I'm sorry I didn't understand what you meant. The change in parameters resulted in a very different result for me, and I wanted to know what happened? I just went back to read the explanation of the parameters, but I am not quite clear about it. Could you help me understand it? 
Thank you!

**Comment by 4ureliek** [comment]
`-s rm` shuffles the TEs where existing TEs are; so the TEs change, but not their positions. This tests whether specific families are enriched or not in their current locations (which is insertion bias + selection (neutral, or not)). This could be extremely biased without an extensive TE annotation of the species of interest.

`-s tss` takes the distance of the TE to its closest annotated TSS and then shuffles it in the same chromosome, to a random TSS, and the distance is conserved. So this tests whether TEs are enriched or not around specific sets/subsets of TSSs (around certain genes), but this is only reliable if most TSS are annotated. This pipeline was written to check TEs and long non coding RNAs, in human/mouse, so very well annotated transcriptomes. 

In both cases, remember that even if you see enrichment and even if it is statistically significant, the reason is difficult to tease out.

Hope this helps! Note there may be more solid pipelines out there for your purposes. I cannot support this anymore, and it was written for TEs & long non coding RNAs in mind.

**Comment by TaoHJiang** [comment]
Thank you  so much！
